### ISSUE TITLE
memory management option

### ISSUE THREAD

**Issue by satoshikumano** [KiiPlatform/kii_json#3]
Currently parser buffer (jsmn token) is allocated in stack and size if fixed.
May not be convenient if there is smaller stack size limitation.

Consider to provide more options and developer can choose optimal way.
- dynamic allocation
- start from lower size and ask for larger size if the given buffer is

**Comment by dairyo** [comment]
@satoshikumano 

動的メモリ確保版(#4)と、スタックサイズ変更版(#5)でそれぞれAPIを作成してみました。

パッと見的には動的メモリ確保版の方がすっきりしそうな予感は有りますね。

どちらにしろ、KiiThingSDK-Embeddedで使うならば、アプリケーション側にアロケータを定義してもらって、それをkii_tかkii_core_t辺りに持たせる必要が生まれそうですね。

それはちょっと面倒そうですね。

他の案も検討してみます。

**Comment by dairyo** [comment]
スタックサイズ変更版(#5)でいく事になりました。

**Comment by dairyo** [comment]
修正が完了したのでcloseします。
